### ISSUE TITLE
Add resource Good Youtube channels list under Youtube Channels Category

### ISSUE THREAD

**Issue by MananDesai54** [developer-student-clubs/dev-resources#1]
Request to Add category and Add resource,

Name : FreeCodeCamp
URL : https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ
Description :  In my opinion this is one the best Channel on youtube
Category : Youtube Channel
Rate plateform/tools :  10 out of 10

- [ ✅ ] I've read the CONTRIBUTING.md
- [ ✅ ] I've used the mentioned resource.

**Comment by MananDesai54** [comment]
@hardikpnsp, @utsav00 please check this

**Comment by Hardik0307** [comment]
Okay, I've added Category.
Go for it  @MananDesai54.

**Comment by MananDesai54** [comment]
Okay
