### ISSUE TITLE
Typo: Correction in FreeCodeCamp description

### ISSUE THREAD

**Issue by utsav00** [developer-student-clubs/dev-resources#13]
There's a typo in the FreeCodeCamp's description where it's `ans` and it should be `and`.

I can do the changes but I'd like to offer a beginner a chance here. Ping here in case of any doubt.

**Comment by lekandev** [comment]
Is it still available, I'd like to do it

**Comment by utsav00** [comment]
Yes, of course, go ahead!

Make sure to read [CONTRIBUTING.md](https://github.com/developer-student-clubs/dev-resources/blob/master/CONTRIBUTING.md
) before getting started.

**Comment by lekandev** [comment]
Thank you, please where is the description exactly, let me do it

**Comment by lekandev** [comment]
I've seen it thank you

**Comment by lekandev** [comment]
I'm done
