### ISSUE TITLE
Remove URL column from the category tables.

### ISSUE THREAD

**Issue by squarebat** [developer-student-clubs/dev-resources#8]
The URL column is unnecessary in all the tables. We can attach a hyperlink to the name of the resource instead. Like this -
[Dev resources](https://github.com/developer-student-clubs/dev-resources/)

**Comment by Hardik0307** [comment]
Right, I have thought that.
But sometimes URL and name of org. are different or meaning can't be conveyed.

**Comment by utsav00** [comment]
When the meaning is ambiguous, the description comes in handy.
We can add some other column that may be required in future in place of link.

**Comment by Hardik0307** [comment]
Agreed.
